### ISSUE TITLE
ClassNotFoundException if the git plugin has been disabled

### ISSUE THREAD

**Issue by LXGaming** [Almighty-Alpaca/JetBrains-Discord-Integration#101]
**Environment**
- Windows 10
- IntelliJ IDEA 2020.1.1
- Discord Integration v1.4.0

**Issue Description**
When the git plugin is disabled the Discord Integration plugin will throw a `ClassNotFoundException` which prevents the plugin from functioning.

Stacktrace: https://gist.github.com/LXGaming/4a14ad4ab22cc7763fd3d2373ac16007

**Comment by Almighty-Alpaca** [comment]
I've just released v1.4.1 whit a fix, should be available on the plugin repo tomorrow.
