### ISSUE TITLE
Constant update notification

### ISSUE THREAD

**Issue by LXGaming** [Almighty-Alpaca/JetBrains-Discord-Integration#102]
**Environment**
- Windows 10
- IntelliJ IDEA 2020.1.1
- Discord Integration v1.4.0

**Issue Description**
Since updating to Discord Integration v1.4.0 I've noticed that every time I open my IDE the first project I open will show a notification informing me that the plugin has been updated. I believe that this notification is only suppose to show once but currently that's not the case.

**Comment by Almighty-Alpaca** [comment]
I've just released v1.4.1 whit a fix, should be available on the plugin repo tomrrow.
