### ISSUE TITLE
 Add support for .mjs

### ISSUE THREAD

**Issue by MrZillaGold** [Almighty-Alpaca/JetBrains-Discord-Integration#106]
At the moment, the plugin treats files with the **.mjs** form as regular files. Files with the **.mjs** format are JavaScript files
![image](https://user-images.githubusercontent.com/42776347/83480393-92c06a00-a4de-11ea-9e6e-efbd620a275e.png)

**Comment by Tisawesomeness** [comment]
`.mjs` is in the [javascript.yaml](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/master/icons/src/main/resources/discord/languages/javascript.yaml) file, but commented out along with a couple other unused extensions. Should I also add any of those extensions?

**Comment by MrZillaGold** [comment]
Only need to add .mjs and also .cjs

**Comment by Tisawesomeness** [comment]
Got it, should be good now!

**Comment by Tisawesomeness** [comment]
@Almighty-Alpaca are there any more I should add?
