### ISSUE TITLE
Can you make the CLion logo transparent? And can you use this logo for C++? Thanks :D

### ISSUE THREAD

**Issue by EthanNeedham** [Almighty-Alpaca/JetBrains-Discord-Integration#112]
[Click here](https://media.discordapp.net/attachments/723223561283567660/723624852434452500/C.png?width=926&height=1041) to see the C++ logo and [click here](https://cdn.freebiesupply.com/logos/large/2x/clion-1-logo-png-transparent.png) to see the transparent CLion logo

**Comment by Almighty-Alpaca** [comment]
There are multiple icon themes, only the Material theme as a background for IDE icons. You should probably take a look at the Classic theme.

**Comment by EthanNeedham** [comment]
Ok, thanks 👍 Will do. To be honest, I kind of forgot what the issue was, either that or what I was bothered by has been updated :D I will close this issue. Thanks and have a great day!
