### ISSUE TITLE
Restart just Discord Integration

### ISSUE THREAD

**Issue by cryptographic1337** [Almighty-Alpaca/JetBrains-Discord-Integration#122]
**SUGGESTION**
In order for the Rich presence to show up in discord, the client must be opened before webstorm. A feature suggestion would be to allow the plugin to be restarted by itself, instead of having to close and reopen the entire IDE. This would allow one to launch the discord client after webstorm has been launched, and still use the rich presence without having to relaunch the IDE.

_**Note: This was an unresolved issue #80 but was closed without a fix**_

**Comment by Almighty-Alpaca** [comment]
> In order for the Rich presence to show up in discord, the client must be opened before webstorm. 

This is not exactly true.

> A feature suggestion would be to allow the plugin to be restarted by itself, instead of having to close and reopen the entire IDE.

The plugin already does that, every 20 seconds until it gets an answer from the Discord client.

> Note: This was an unresolved issue #80 but was closed without a fix

The issue (restarting the integration/resetting the connection) was fixed, it seems like it just doesn't fix the connetion.

**Comment by Almighty-Alpaca** [comment]
Anyway, we're currently in the process of moving the new [GameSDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide) which hopefully fixed the problems some people experience.
