### ISSUE TITLE
Not working with Discord 0.0.12 on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by onyxcode** [Almighty-Alpaca/JetBrains-Discord-Integration#124]
It doesn't throw any errors. It just doesn't show up. Any ideas?

**Comment by InfRandomness** [comment]
Hello, please check in the plugin settings (File -> Settings -> Discord|File -> Settings -> Other Settings -> Discord) if you do have any red boxes showing up, the text in those red boxes (if any) should tell you what's going wrong.

If you do have difficulties figuring it all out I invite you to join the discord server where can can give further help easier.

**Comment by onyxcode** [comment]
Oh. I see the issue now :/

![image](https://user-images.githubusercontent.com/58049576/93231985-5dffb800-f747-11ea-91b1-dd78bd053c84.png)
