### ISSUE TITLE
New project settings having an issue

### ISSUE THREAD

**Issue by InfRandomness** [Almighty-Alpaca/JetBrains-Discord-Integration#131]
I created a new project today with the plugin installed in my IDE and when I went inside my IDE to set the project settings I saw that 
![image](https://user-images.githubusercontent.com/43730933/97043339-9ed2c400-1572-11eb-877b-9053a3a9ca39.png)
for some reason, there's an "ask" field, and whenever I switch to another value, the field ask disappear.

That felt weird to see and I don't know if that's a bug or not so I reported it just in case

**Comment by Almighty-Alpaca** [comment]
This actually is intentional: When you didn't click the pop-up yet the value is set to "Ask". But it doesn't make sense to manually select that as visibility because it would just mean that the next time you open the project the pop-up would show again.

**Comment by InfRandomness** [comment]
yeah, I see, thanks !
