### ISSUE TITLE
Update Kotlin Logo on the rich presence

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Almighty-Alpaca/JetBrains-Discord-Integration#132]
This is a nitpick, but the Kotlin logo that the rich presence uses is... ugly.

Would be nice if the logo was updated to the current Kotlin logo!

**Comment by dblanovschi** [comment]
Hi! There are 4 logos for Kotlin, belonging to different themes. You can choose which theme to use in `Settings > Other settings > Discord`.

Here's how they look:
- In the material theme:

<img src="https://raw.githubusercontent.com/Almighty-Alpaca/JetBrains-Discord-Integration/master/icons/src/main/resources/discord/themes/material/kotlin.png" width="100" height="100"></img>

- In the flat theme:

<img src="https://raw.githubusercontent.com/Almighty-Alpaca/JetBrains-Discord-Integration/master/icons/src/main/resources/discord/themes/flat/kotlin.png" width="100" height="100"></img>

- In the classic theme(I think this is what you mean by the current Kotlin logo):

<img src="https://raw.githubusercontent.com/Almighty-Alpaca/JetBrains-Discord-Integration/master/icons/src/main/resources/discord/themes/classic/kotlin.png" width="100" height="100"></img>

- In the atom theme:

<img src="https://raw.githubusercontent.com/Almighty-Alpaca/JetBrains-Discord-Integration/master/icons/src/main/resources/discord/themes/atom/kotlin.png" width="100" height="100"></img>

**Comment by MrPowerGamerBR** [comment]
Thank you! I didn't know that there was a settings tab for the plugin (I only found out the per-project settings in the "Tools" section) :)
