### ISSUE TITLE
Spams the everloving shit out of idea.log

### ISSUE THREAD

**Issue by SirNapkin1334** [Almighty-Alpaca/JetBrains-Discord-Integration#133]
The plugin sends `Discord - Sending new presence` to `idea.log` every 5 seconds, causing the logs to be inflated to absolutely massive sizes. On a good day, over half of the entire fucking log will just be `Discord - Sending new presence`. I believe this massive inflation of log sizes might also be why I am unable to upload my logs to YouTrack because they are just too big. Please, fix this, or at least add an option to turn it off.

<img width="1604" alt="image" src="https://user-images.githubusercontent.com/31591796/98427785-6d1e2a80-2053-11eb-919f-2f8fbf91500a.png">

<img width="562" alt="image" src="https://user-images.githubusercontent.com/31591796/98427799-7c04dd00-2053-11eb-9241-6bd05e294409.png">

<img width="913" alt="image" src="https://user-images.githubusercontent.com/31591796/98427806-80c99100-2053-11eb-9162-ef38711eda0f.png">

**Comment by SirNapkin1334** [comment]
Also, it appears that there are over 10000 instances of other messages from discord. The regex `\d{4}-\d\d-\d\d (?:\d\d:){2}\d\d,\d{3} \[\d+\] +INFO - +Discord - .*\n` found 46,896 matches.

**Comment by Almighty-Alpaca** [comment]
Fixed in #137
