### ISSUE TITLE
Doesn't detect ProjectName on JetBrains Rider

### ISSUE THREAD

**Issue by van800** [Almighty-Alpaca/JetBrains-Discord-Integration#135]
![image](https://user-images.githubusercontent.com/1482681/98830142-57857800-243a-11eb-8472-6cb8ca2a53b5.png)

**Comment by dblanovschi** [comment]
Hello! I have a feeling you used `${ProjectName}` from the templates in the application preview tab. If that is the case, the plugin will just ignore the values for the project and file and replace them with dummy ones.

Here is a table of what data and where it is available:

| Data                             | Application     | Project        | File         |
|-------------------------------|-------------------|------------------|-------------|
|`$ApplicationVersion`   | Available        | Availabe       | Available |
|`$ProjectName`            | Not available | Available       | Available |
|`$ProjectDescription`    | Not available  | Available       | Available |
|`$VcsBranch`                | Not available  | Available       | Available |
|`$FileName`                  | Not available  | Not available | Available |
|`$FileNameUnique`       | Not available  | Not available | Available |
|`$CaretLine`                  | Not available  | Not available | Available |
|`$LineCount`                 | Not available  | Not available | Available |
|`$Language`                 | Not available  | Not available | Available |
|`$ModuleName`            | Not available  | Not available | Available |
|`$PathInModule`           | Not available  | Not available | Available |
|`$FileSize`                     | Not available  | Not available | Available |
|`$FileIsWritable`            | Not available  | Not available | Available |
|`$IsTextEditor`               | Not available  | Not available | Available |
|`$DebuggerActive`        | Not available  | Available       | Available |

Where the data is not available, it will be [replaced with a dummy value in the preview](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/master/plugin/src/main/kotlin/com/almightyalpaca/jetbrains/plugins/discord/plugin/settings/gui/preview/PreviewRenderer.kt#L482-L505), for example "Dummy project" for the project name, so a value is always displayed in the preview(note: they will be replaced with empty strings when rendered for discord).

**Comment by van800** [comment]
Ok, I have checked several projects now and only for some of them Project Name is not detected.

![image](https://user-images.githubusercontent.com/1482681/98838822-10e94b00-2445-11eb-8a91-55793e0a969c.png)

**Comment by van800** [comment]
Hm, when I checked the same on Discord itself - it showed up fine.
So the issue is only in the preview.
