### ISSUE TITLE
Feature request: placeholders for "custom"

### ISSUE THREAD

**Issue by bananasmoothii** [Almighty-Alpaca/JetBrains-Discord-Integration#140]
I wanted my first line to be "Project name - file" but this option doesn't exist. Would it be possible to add placeholders for the "custom" mode, so I can enter "%name% - %file%" for example ?

**Comment by dblanovschi** [comment]
Hello! This has been implemented in #108 (you can get it in EAP builds and you can find the reference [here](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/master/plugin/templates.adoc)). Duplicate of #117. If you have any questions feel free to mention me or ask in the `#support` channel on the discord server.

**Comment by bananasmoothii** [comment]
Hello, thanks ! Is there any wiki, to know what are the placeholders I can use ?

**Comment by dblanovschi** [comment]
Yes, in [the reference](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/blob/master/plugin/templates.adoc#variables).

**Comment by bananasmoothii** [comment]
thanks !

**Comment by bananasmoothii** [comment]
Uhm, placeholders are not working
![profile](https://user-images.githubusercontent.com/45853225/100089610-3e28f680-2e52-11eb-99ae-af669c44bfb7.PNG)

**Comment by dblanovschi** [comment]
Is that`1.5.0+11`?

**Comment by bananasmoothii** [comment]
![version_](https://user-images.githubusercontent.com/45853225/100089868-ad064f80-2e52-11eb-9a71-6be5a2b8fbff.PNG)

**Comment by dblanovschi** [comment]
They're not available on stable yet. You can get `1.5.0+11` from <https://plugins.jetbrains.com/plugin/10233-discord-integration/versions/eap>, or alternatively build from master branch.

**Comment by bananasmoothii** [comment]
thanks, it works !
