### ISSUE TITLE
Plugin not working after first installation disabling logs

### ISSUE THREAD

**Issue by rocambin** [Almighty-Alpaca/JetBrains-Discord-Integration#143]
### What actually happens

The plugin did not work after the first installation disabling the notification logs:
- `com.almightyalpaca.intellij.plugins.discord.project.show` ;
- `com.almightyalpaca.intellij.plugins.discord.project.update`.

### What is supposed to happen

The plugin should have planned users skipping the sticky balloon notifications.

### What I've tried...

- Restarted IntelliJ ;
- Restarted Discord.

### Current solution ✅

Simply resintalling the plugin worked for me.

**Comment by Almighty-Alpaca** [comment]
You can change those settings at any time under `Tools > Discord` or under `Settings > (Other Settings) > Discord > Project`
