### ISSUE TITLE
Uncaught plugin Startup Issue.

### ISSUE THREAD

**Issue by Unthrottled** [Almighty-Alpaca/JetBrains-Discord-Integration#162]
Hey! So this issue is a bit weird.

I currently [maintain this JetBrains plugin](https://github.com/one-dark/jetbrains-one-dark-theme), and I have sentry installed. Sentry likes to catch un-caught exceptions and send them to me for some reason. There was a `IllegalStateException getService(T::class.java) must not be null`

[Here's a link to the stacktrace](https://sentry.io/share/issue/77fc13f6e5fb4a80860688d2b378f702/), Dunno if it's something you are aware of. It's only happened twice, so no big deal. I can't tell you more, because it doesn't tell me the version of the plugin or what platform it's running on, sorry!

**Comment by Almighty-Alpaca** [comment]
I've also seen error before, only on 2021.2 EAP though. But as I've also experienced it coming from the Code With Me plugin I'll assume it's an issue within IntelliJ for now.
