### ISSUE TITLE
Icon hover text conflict

### ISSUE THREAD

**Issue by mustafaulker** [Almighty-Alpaca/JetBrains-Discord-Integration#180]
- The file name is shown when hovering over the large icon.
![big](https://user-images.githubusercontent.com/48808788/127525221-eb247e2d-00e9-4402-aa2c-f13beddfe357.jpg)

- App version is shown when hovering over the small icon.
![small](https://user-images.githubusercontent.com/48808788/127525229-db3a69c6-e7cf-43e2-961f-0e27a131b342.jpg)

**Comment by dblanovschi** [comment]
You forgot to swap the texts when you swapped the icons

**Comment by mustafaulker** [comment]
Oh sorry, thank you.
