### ISSUE TITLE
Plugin can't find discord

### ISSUE THREAD

**Issue by Lavariator** [Almighty-Alpaca/JetBrains-Discord-Integration#181]
Issue:
The plugin says it can't find discord, even though it's open. I experienced this issue, when i opened IntelliJ IDEA first and then discord.

Steps to Reproduce:
1. Open IntelliJ IDEA Ultimate 
2. Open Discord
3. See in the settings the <a href="http://i.prntscr.com/e8xohfWxQHGnYr84IpEnhw.png">error message</a>.

IDE Information:
Plugin Version: 1.7.0
IDE Name: IntelliJ IDEA Ultimate
IDE Version: 2021.2 (Build #IU-212.4746.92)

Discord Information:
Type: Application
Version: Stable 91734 (Build e70905d)

Device Information:
OS: Windows 10 Home 64-Bit 
Version: 21H1 (Build 19043.1110)

**Comment by Almighty-Alpaca** [comment]
The warnings in the settings are purely informational at the moment. The information the plugin checks is very limited and also doesn't update dynamically. As long as Discord is still showing the activity there's nothing to worry about.
