### ISSUE TITLE
Plugin stills runs while my IDE is closed

### ISSUE THREAD

**Issue by DevShaded** [Almighty-Alpaca/JetBrains-Discord-Integration#183]
Discord Intergration Plugin still runs while my IDE is closed and it shows that I'm coding while im not

![image](https://user-images.githubusercontent.com/49687450/127853333-3d12349a-5928-4b02-a79c-fb28a708f5a9.png)

![image](https://user-images.githubusercontent.com/49687450/127853215-ae148ddd-1fed-4d25-9f32-857896471dd6.png)

**Comment by Almighty-Alpaca** [comment]
I have seen that bug a few times myself, but I'm unsure of how that's possible. When the IDE is closed then so is the connection to the client. Currently my bet is on a bug in the Discord client.

**Comment by DevShaded** [comment]
Understood, I really don't have this issue anymore.
