### ISSUE TITLE
Allow overriding the rich pressence

### ISSUE THREAD

**Issue by avi12** [Almighty-Alpaca/JetBrains-Discord-Integration#187]
Right now, Discord Integration either reports the status when a JetBrains IDE is running or doesn't report at all
I wish that it will only be reporting when nothing else is running in the background
So, for example, if I listen to Spotify, Discord will pick Spotify up; if I play a game, it will pick that game up; if I don't run anything, it will pick the active JetBrains IDE up

**Comment by Almighty-Alpaca** [comment]
When there are multiple applications with rich presence Discord decides what it wants to prioritize. The plugin has no control over that.
