### ISSUE TITLE
Simply not working.

### ISSUE THREAD

**Issue by 3jq** [Almighty-Alpaca/JetBrains-Discord-Integration#217]
All of the other discord rich presence interpretations work.

Plugin Version: 1.8.0
Intellij Version: 2021.1.1
OS: Windows 10
Discord: Stable/Canary (doesn't work on both)

I already have tried: reinstalling the plugin, reenabling the plugin, changing plugin's settings

**Comment by Toliak** [comment]
I have the same issue after upgrading the WebStorm. Before the upgrade worked correctly.
```
WebStorm 2021.3.2
Build #WS-213.6777.57, built on January 31, 2022
Licensed to <hidden>
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2028M
Cores: 12
Non-Bundled Plugins:
    de.ax.powermode (100.001)
    com.wakatime.intellij.plugin (13.1.13)
    com.verilang (0.1.8)
    nl.rubensten.texifyidea (0.7.15)
    mobi.hsz.idea.gitignore (4.3.0)
    com.intellij.database (213.6777.57)
    com.almightyalpaca.intellij.plugins.discord (1.8.0)
```

**Comment by alceawdwd** [comment]
but i wrong the version

**Comment by 3jq** [comment]
Found a fix for me:
If games richpresence in discord are disabled, then the intellij rpc also will not work.

**Comment by InfRandomness** [comment]
Yes that's because "games richpresence" are actually just "richpresences", and we use "richpresences"

**Comment by j4cegh** [comment]
> Yes that's because "games richpresence" are actually just "richpresences", and we use "richpresences"

Part of why rich presence says "Playing" instead of, "Using" or something.
