### ISSUE TITLE
Status not updating on 2022.1 EAP

### ISSUE THREAD

**Issue by ConsoleLogLuke** [Almighty-Alpaca/JetBrains-Discord-Integration#218]
On IntelliJ IDEA 2022.1 EAP, my Discord status doesn't update unless I run "Force reconnect". When I first open IDEA, my status isn't set at all and every time I switch files, I need to force reconnect again to get it to update.

I'm using the latest version of the plugin (1.8.0) on Windows 11. Everything worked fine until I updated to the first EAP build of IDEA 2022.1.

**Comment by Almighty-Alpaca** [comment]
Support for 2022.1 is being worked on

**Comment by Almighty-Alpaca** [comment]
Fixed in v1.9.0
