### ISSUE TITLE
Add support to other Discord clients

### ISSUE THREAD

**Issue by V1li** [Almighty-Alpaca/JetBrains-Discord-Integration#245]
For example ![WebCord](https://github.com/SpacingBat3/WebCord) isn't detected when trying to use it with the plugin.

**Comment by dnbln** [comment]
https://github.com/SpacingBat3/WebCord/blob/master/docs/Features.md#list-of-currently-implemented-and-planned-webcords-features

There are differences between the web app and the discord client, one of them being the RPC socket that's needed for this plugin to work. The socket is provided by the discord client, and there is not much a program can do in terms of rich presence without it.
