### ISSUE TITLE
Add ability to set the default project visibility

### ISSUE THREAD

**Issue by OakleyCord** [Almighty-Alpaca/JetBrains-Discord-Integration#255]
Add the ability change the visibility in projects by default because sometimes you don't want to instantly share your current project :)

**Comment by dnbln** [comment]
> If you don't want to be asked every time you can change the default in the default settings for new projects
https://www.jetbrains.com/help/idea/configure-project-settings.html#new-default-settings 

(From `#faq` on discord)
