### ISSUE TITLE
Project with multiple modules says 'Working on <first module>'

### ISSUE THREAD

**Issue by ramidzkh** [Almighty-Alpaca/JetBrains-Discord-Integration#28]
Title says it all. I have a Project with 2 Gradle modules (not Gradle submodules). When I opened IntelliJ IDEA it says the first module I have, in my case 'client'
![](https://i.imgur.com/seuUriE.png)
![](https://i.imgur.com/4MC1aJq.png)

Even when I start working on a file in the other module, it still says 'client'

I would of thought that it would say the Project name, not the module name, or show both

**Comment by AregevDev** [comment]
I think there is an event that executes when a module has been ch

**Comment by LeafHacker** [comment]
I'm in favour of showing the project name over the module name.

Perhaps this issue should focus on updating the module when it changes while another could suggest an option to show project name over module name.

**Comment by AregevDev** [comment]
Could be, if the module fix isn't working

**Comment by Almighty-Alpaca** [comment]
When I create an empty project and then create two modules inside it the plugin still shows the project's name. I know I've succeeded once in re-creating the behavior described above, but I can't seems to be able to do that now. Can one of you either write down the steps or send me a project that behaves this way?

**Comment by Almighty-Alpaca** [comment]
Closing this due to the plugin rewrite.
