### ISSUE TITLE
Exception on startup after new update

### ISSUE THREAD

**Issue by Ezhidzee** [Almighty-Alpaca/JetBrains-Discord-Integration#287]
Attached the file with the error text
After the new update, the extension worked normally, but after restarting one program, this error began to appear
[stacktrace.txt](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/files/10303597/stacktrace.txt)

**Comment by fabio1999ita** [comment]
to me this happen when i switch project without closing ide

![image](https://user-images.githubusercontent.com/27001568/209571200-d64ef3bb-d464-4f85-bb4d-d374b7e6a7c7.png)
![image](https://user-images.githubusercontent.com/27001568/209571230-80aa97c6-2772-4da1-9b6c-861a4c6adeee.png)

**Comment by Ezhidzee** [comment]
The error went away on its own after a couple of days.
