### ISSUE TITLE
Exeption in Discord Integration (1.11.0)

### ISSUE THREAD

**Issue by Quenteez** [Almighty-Alpaca/JetBrains-Discord-Integration#307]
I think this is due to the fact that I listen to Spotify when I start Intellij.

**stacktrace:**
https://pastebin.com/raw/CyFVTZPP

**Comment by KamelaJda** [comment]
To fix this, u need to set the text on a small icon, like this
![image](https://user-images.githubusercontent.com/39656013/221177079-7f61021d-69a8-48ed-98d6-dcfbfab59780.png)
