### ISSUE TITLE
[Suggest] Add Support RustRover

### ISSUE THREAD

**Issue by thedtvn** [Almighty-Alpaca/JetBrains-Discord-Integration#380]
i have install it on RustRover and it not show on discord

**Comment by itsTyrion** [comment]
https://github.com/Azn9/Jetbrains-Discord-Integration there's this fork with RustRover support https://github.com/Azn9/Jetbrains-Discord-Integration

**Comment by thedtvn** [comment]
> https://github.com/Azn9/Jetbrains-Discord-Integration there's this fork with RustRover support https://github.com/Azn9/Jetbrains-Discord-Integration

thank
