### ISSUE TITLE
Ability to use project name as Application name

### ISSUE THREAD

**Issue by Ashark** [Almighty-Alpaca/JetBrains-Discord-Integration#387]
Would it be possible to use the Project name instead of IDE name as Application name?

**Comment by Azn9** [comment]
This is not possible. The application name is the one provided in the discord developer portal and cannot be changed elsewhere.

**Comment by Ashark** [comment]
Ah, that is unfortunate. So you have a several pre-defined applications in discord side named "PyCharm", "PyCharm Community", etc. And to be able to change it, one may need to register as a developer in discord, and create/update/change that name there. Am I correct?

**Comment by Azn9** [comment]
> Ah, that is unfortunate. So you have a several pre-defined applications in discord side named "PyCharm", "PyCharm Community", etc. And to be able to change it, one may need to register as a developer in discord, and create/update/change that name there. Am I correct?

Exactly!

**Comment by Ashark** [comment]
Ok. Thanks for quick responce!
