### ISSUE TITLE
[Feature request] Dynamic application name for different Jetbrains products

### ISSUE THREAD

**Issue by UltimatePancake** [Almighty-Alpaca/JetBrains-Discord-Integration#4]
Would it be possible for this plugin to display if I'm using other Jetbrains products, e. g. PyCharm, DataGrip, would be nice to have.

Will check how you're doing it and might PR if I find some time. Just putting this here for posterity.

**Comment by MinnDevelopment** [comment]
Discord is using the application name (in the developers dashboard)

**Comment by Almighty-Alpaca** [comment]
As Minn already mentioned Discord uses the name of the application. That means the only way to achive that is creating one application per IDE. That is not only really ugly but would also require me to have two separate discord accounts just for the applications as you can only have 10 applications per account (there are ~15 IDEs).

There already is [an issue on the discord-rpc git](discordapp/discord-rpc/issues/54) about this but it doesn't seem like they intent to implement dynamic names at least in the near future.

**Comment by GeoffreyWesthoff** [comment]
Would "a IntelliJ IDEA" suffice as a name

**Comment by Almighty-Alpaca** [comment]
You probably mean "an IntelliJ IDE`, right?
I'd personally "a Jetbrains IDE", but I'm open for other opinion.

**Comment by ArtutoGamer** [comment]
I vote for "JetBrains IDE"

**Comment by ArtutoGamer** [comment]
@Almighty-Alpaca Is this gonna be fixed? It looks weird using WebStorm (for example) and showing IntelliJ

_Sent from my LG K10 Power using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Almighty-Alpaca** [comment]
Right, completely forgot about this, sry. Fortunately I can change that without having to push an update. Fixed now.

I'll still leave this issue open as feature request for dynamic names in case discord ever makes that possible.

**Comment by ArtutoGamer** [comment]
Nice :grinning:

**Comment by Almighty-Alpaca** [comment]
This has been implemented in the rewrite using a huge amount of applications.
