### ISSUE TITLE
New gradle logo

### ISSUE THREAD

**Issue by duncte123** [Almighty-Alpaca/JetBrains-Discord-Integration#41]
In a recent update of intellij (2018.2 beta 2) it has a new gradle logo, hereby my request to update the logo

![New logo](https://user-images.githubusercontent.com/8843386/42273586-dfc9b7ce-7f89-11e8-942a-1d14b64381cd.png)

**Comment by Almighty-Alpaca** [comment]
This has been implemented in the rewrite.
