### ISSUE TITLE
Add option to never show projects

### ISSUE THREAD

**Issue by Almighty-Alpaca** [Almighty-Alpaca/JetBrains-Discord-Integration#48]

**Comment by miyaokamarina** [comment]
Maybe options to hide current project and/or files in current project alongside with customizable defaults will be better?

**Comment by Almighty-Alpaca** [comment]
Just added support for something like this in the rewrite I'm currently working on. 
I've been dropping preview builds in the Discord server every now and then so feel free to joins there if you don't want to wait until the official release (link is in the readme).

**Comment by AregevDev** [comment]
You can also build the project from source and install the output plug-in in your IDE, if you have the right dev environment.

**Comment by Almighty-Alpaca** [comment]
This has been implemented in the rewrite.
