### ISSUE TITLE
.gitignore integration

### ISSUE THREAD

**Issue by Santana1053** [Almighty-Alpaca/JetBrains-Discord-Integration#49]
Currently there is an option to `Hide` or `Show "Reading"` for files that are read-only.

I would like to request that these rules also apply to rules files that are being ignored.

**Comment by Almighty-Alpaca** [comment]
I have to say I really like the idea. 
Could also be implemented together with hiding files that are marked as excluded in intellij.

**Comment by Almighty-Alpaca** [comment]
I'll wait with this until the .ignore plugin has fully been integrated into IntelliJ.

**Comment by Almighty-Alpaca** [comment]
This has already been implemented as of v1.4.0 (just forgot to close the issue :grimacing:)
