### ISSUE TITLE
Clojure files not recognised

### ISSUE THREAD

**Issue by skykanin** [Almighty-Alpaca/JetBrains-Discord-Integration#57]
![image](https://user-images.githubusercontent.com/3789764/53116749-aa721a00-3549-11e9-85fc-cf68c5e7064f.png)

`.clj` and .`cljs` aren't recognised by the plugin when being edited even though the repository containing all the icons does have a Clojure material theme [icon](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration-Icons/blob/master/icons/material/clojure.png).

**Comment by Almighty-Alpaca** [comment]
I'm currently rewriting the whole plugin because the current codebase is rather... let's just say ugly. That includes how this repository is structured. 

I'm pretty sure the issue resolves itself once the rewrite progress has reached a stable state and people can start testing it.

**Comment by skykanin** [comment]
Nice, in the mean time I made this PR: https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/pull/58

**Comment by Almighty-Alpaca** [comment]
The rewrite has now been pushed and will be available in the next few days.
