### ISSUE TITLE
.EJS files are not recognised

### ISSUE THREAD

**Issue by Cairo2k18** [Almighty-Alpaca/JetBrains-Discord-Integration#60]
On discord there is no rich presence image for .ejs files..

**Comment by Almighty-Alpaca** [comment]
The rewrite that's currently been worked on already has support for it. I'll officially be released in the next few days. 

If you want to check it out now feel free to join the [Discord](https://discord.gg/SvuyuMP) server and check the `#announcements` channel for instructions on how to get the previews.

**Comment by Cairo2k18** [comment]
Thanks!
