### ISSUE TITLE
Doesn't work on linux

### ISSUE THREAD

**Issue by WhileInside** [Almighty-Alpaca/JetBrains-Discord-Integration#64]
Your plugin doesn't work on Linux Mint 19.1

http://i.imgur.com/pr9VIi3.png

**Comment by MinnDevelopment** [comment]
It works if you don't run discord/intellij in a sandbox.

**Comment by mdashlw** [comment]
![image](https://user-images.githubusercontent.com/34678047/64316619-0409d580-cfbe-11e9-9d21-60e95f210cd3.png)

**Comment by Almighty-Alpaca** [comment]
@mdashlw pls stop posting nonsense off-topic images

**Comment by Almighty-Alpaca** [comment]
@WhileInside as Minn already pointed out the plugin does not work when using any sandboxed environment such as Flatpack or Snap. The latter includes applications distributed via the Ubuntu Software Center.

Also, feel free to join the [Discord server](https://discord.gg/SvuyuMP) if you need additional help.

**Comment by mdashlw** [comment]
> @mdashlw pls stop posting nonsense off-topic images

bruh if you didnt understand that, it doesnt mean thats off-topic, but ok
