### ISSUE TITLE
Way to select which Discord instance?

### ISSUE THREAD

**Issue by retnikt** [Almighty-Alpaca/JetBrains-Discord-Integration#66]
I use both Stable and PTB Discord Desktop on my Ubuntu dev machine for home and work use (with two separate Discord accounts respectively). I would like to be able to select which of these clients, or both, the plugin displays my activity in. Currently I think whichever discord instance has been open for longest is used.

This may not be possible because of Discord Rich Presence limitations, in which case I understand.

**Comment by Almighty-Alpaca** [comment]
You guess is correct. This isn't possible in a useful way with [Disord's RPC library](https://github.com/discordapp/discord-rpc/issues/203).

**Comment by dblanovschi** [comment]
The discord gamesdk might help with this one:
https://discord.com/developers/docs/game-sdk/sdk-starter-guide#testing-locally-with-two-clients

**Comment by Almighty-Alpaca** [comment]
Closing this in favor of #232
