### ISSUE TITLE
Custom text for icon

### ISSUE THREAD

**Issue by LeptoFlare** [Almighty-Alpaca/JetBrains-Discord-Integration#68]
This was closed previously (without explanation) But it would be great to have custom values for image text

**Comment by Almighty-Alpaca** [comment]
I don't think I've ever closed this feature request but this is actually a thing I'm planning to add in the future.

**Comment by LeptoSpira** [comment]
Would there be a way to hotlink the image? (clicking the image brings you to a link)

**Comment by Almighty-Alpaca** [comment]
Unfortunately not. Discord doesn't support links/Markdown etc. in your status.

**Comment by LeptoSpira** [comment]
Unfortunate, I might make a feature request

**Comment by Almighty-Alpaca** [comment]
This has been implemented in v1.5.0.
