### ISSUE TITLE
Doesn't seem to be working for Mac OS

### ISSUE THREAD

**Issue by jclevesque** [Almighty-Alpaca/JetBrains-Discord-Integration#70]
Mac OS 10.14.5 Mojave 
Plugin version : 1.0.1

PyCharm 2019.2.3 (Professional Edition)
Build #PY-192.6817.19, built on September 25, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: 
Non-Bundled Plugins: com.almightyalpaca.intellij.plugins.discord, BashSupport

I have enabled rich presence overall and enabled it for project as well, in case this has an impact. Restarted both PyCharm and then discord, to no avail. What can I do to debug this?

**Comment by Almighty-Alpaca** [comment]
As has already been pointed out the plugin does usually work in macOS. However, sometimes the RPC connection has a few problems. Here's a list of common problems/fixes:

- The plugin does not work with the web version of Discord
- Check Settings -> Game Activity -> Display running game as status message
- Make sure your IDE isn't added as a game in Discord
- Start Discord before starting the IDE
- Restarting both Discord and the IDE
- Restarting your PC
- Reinstalling the plugin

Sry for the late response.

**Comment by jclevesque** [comment]
Tried all of these things, still nothing. Oh well

**Comment by Almighty-Alpaca** [comment]
Sorry I completely forgot about this issue. Did you ever get the plugin to work?
