### ISSUE TITLE
Restart just JetBrains Discord Integration

### ISSUE THREAD

**Issue by cryptographic1337** [Almighty-Alpaca/JetBrains-Discord-Integration#80]
**SUGGESTION**
In order for the Rich presence to show up in discord, the client must be opened before webstorm. A feature suggestion would be to allow the plugin to be restarted by itself, instead of having to close and reopen the entire IDE. This would allow one to launch the discord client after webstorm has been launched, and still use the rich presence without having to relaunch the IDE.

**Comment by misuti** [comment]
Also the icons do not show up until I
1. Turn off rich presence
2. Apply
3. Turn it back on
4. Apply

**Comment by cryptographic1337** [comment]
@misuti open a new issue for this.

**Comment by misuti** [comment]
?

**Comment by Almighty-Alpaca** [comment]
This is now possible in v1.3.0. It should also try to reconnect itself if it couldn't connect after 30 seconds.
