### ISSUE TITLE
Exception on Launch

### ISSUE THREAD

**Issue by Buzzec** [Almighty-Alpaca/JetBrains-Discord-Integration#88]
A blinking red explanation point appears in clion whenever I launch and every now and then. The exception doesn't seem to affect the plugin working and I can clear it or just ignore it without problems. Also occurs in intellij.

Clion version: 2020.1
Intellij version: 2020.1

stacktrace.txt: https://pastebin.com/fNGJcN5g
thraedDump.txt: https://pastebin.com/SEvsH1At

**Comment by Almighty-Alpaca** [comment]
This should be fixed in v1.3.0
