### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Zerogoki00** [Almighty-Alpaca/JetBrains-Discord-Integration#90]
I installed this plugin from repository but I don't see "Discord" in Settings --> Tools. There is Discord entry in Tools but it's greyed out
![93A7f3n](https://user-images.githubusercontent.com/61648511/80372172-c5ea5a80-889b-11ea-8877-bd7fcd5eba22.png)

**Comment by InfRandomness** [comment]
Hi, on the 1.2.0 update, the configuration tab isn't at Settings | Tools anymore but has been moved over to Settings | Other Settings | Discord or Settings | Discord in some cases.

**Comment by Zerogoki00** [comment]
The problem was in my java version. JRE 8 is unsupported by this plugin.
