### ISSUE TITLE
[Feature Request] Add "Module Name" option to be shown in Rich Presence

### ISSUE THREAD

**Issue by ColaIan** [Almighty-Alpaca/JetBrains-Discord-Integration#96]
Hello, I'd like to request a feature to allow the "Module Name" to be shown in the Rich Presence, thanks!

**Comment by Almighty-Alpaca** [comment]
This was implemented together with templates and will be available in the next release

**Comment by Likqez** [comment]
Just curious, when will this feature be released?

**Comment by Almighty-Alpaca** [comment]
Just pushed it
